#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Please provide a filename as an argument."
    exit 1
fi

filename="$1"
output_dir="build"
output_file="$output_dir/$filename"

if [ ! -d "$output_dir" ]; then
    mkdir "$output_dir"
fi

g++ "$filename.cpp" -o "$output_file"

if [ $? -eq 0 ]; then
    echo "Compilation successful."
    "$output_file"
else
    echo "Compilation failed."
fi
